"""Add hotels table with id and name columns

Revision ID: 33729f88413a
Revises: 5e4b67de4011
Create Date: 2024-04-03 11:22:19.350612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33729f88413a'
down_revision = '5e4b67de4011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    # ### end Alembic commands ###
