"""Add age column to examples table

Revision ID: 5e4b67de4011
Revises: 8926db5ad9b1
Create Date: 2024-04-03 10:55:54.301202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4b67de4011'
down_revision = '8926db5ad9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
