"""Added price column to examples table

Revision ID: 8926db5ad9b1
Revises: f421f169bac4
Create Date: 2024-04-03 10:23:53.720442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8926db5ad9b1'
down_revision = 'f421f169bac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examples', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
